package smartcaravans.constat.client.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

object BlueColors {
    private val primaryLight = Color(0xFF0D41A7)
    private val onPrimaryLight = Color(0xFFFFFFFF)
    private val primaryContainerLight = Color(0xFFDBE1FF)
    private val onPrimaryContainerLight = Color(0xFF324478)
    private val secondaryLight = Color(0xFF595E72)
    private val onSecondaryLight = Color(0xFFFFFFFF)
    private val secondaryContainerLight = Color(0xFFDDE1F9)
    private val onSecondaryContainerLight = Color(0xFF414659)
    private val tertiaryLight = Color(0xFF815512)
    private val onTertiaryLight = Color(0xFFFFFFFF)
    private val tertiaryContainerLight = Color(0xFFFFDDB6)
    private val onTertiaryContainerLight = Color(0xFF643F00)
    private val errorLight = Color(0xFFBA1A1A)
    private val onErrorLight = Color(0xFFFFFFFF)
    private val errorContainerLight = Color(0xFFFFDAD6)
    private val onErrorContainerLight = Color(0xFF93000A)
    private val backgroundLight = Color(0xFFFAF8FF)
    private val onBackgroundLight = Color(0xFF1A1B21)
    private val surfaceLight = Color(0xFFFAF8FF)
    private val onSurfaceLight = Color(0xFF1A1B21)
    private val surfaceVariantLight = Color(0xFFE2E2EC)
    private val onSurfaceVariantLight = Color(0xFF45464F)
    private val outlineLight = Color(0xFF757680)
    private val outlineVariantLight = Color(0xFFC5C6D0)
    private val scrimLight = Color(0xFF000000)
    private val inverseSurfaceLight = Color(0xFF2F3036)
    private val inverseOnSurfaceLight = Color(0xFFF1F0F7)
    private val inversePrimaryLight = Color(0xFFB4C5FF)
    private val surfaceDimLight = Color(0xFFDAD9E0)
    private val surfaceBrightLight = Color(0xFFFAF8FF)
    private val surfaceContainerLowestLight = Color(0xFFFFFFFF)
    private val surfaceContainerLowLight = Color(0xFFF4F3FA)
    private val surfaceContainerLight = Color(0xFFEEEDF4)
    private val surfaceContainerHighLight = Color(0xFFE8E7EF)
    private val surfaceContainerHighestLight = Color(0xFFE3E2E9)

    private val primaryLightMediumContrast = Color(0xFF213367)
    private val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
    private val primaryContainerLightMediumContrast = Color(0xFF596BA2)
    private val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    private val secondaryLightMediumContrast = Color(0xFF303648)
    private val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
    private val secondaryContainerLightMediumContrast = Color(0xFF676C81)
    private val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    private val tertiaryLightMediumContrast = Color(0xFF4E3000)
    private val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
    private val tertiaryContainerLightMediumContrast = Color(0xFF926420)
    private val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    private val errorLightMediumContrast = Color(0xFF740006)
    private val onErrorLightMediumContrast = Color(0xFFFFFFFF)
    private val errorContainerLightMediumContrast = Color(0xFFCF2C27)
    private val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
    private val backgroundLightMediumContrast = Color(0xFFFAF8FF)
    private val onBackgroundLightMediumContrast = Color(0xFF1A1B21)
    private val surfaceLightMediumContrast = Color(0xFFFAF8FF)
    private val onSurfaceLightMediumContrast = Color(0xFF101116)
    private val surfaceVariantLightMediumContrast = Color(0xFFE2E2EC)
    private val onSurfaceVariantLightMediumContrast = Color(0xFF34363E)
    private val outlineLightMediumContrast = Color(0xFF51525B)
    private val outlineVariantLightMediumContrast = Color(0xFF6B6C75)
    private val scrimLightMediumContrast = Color(0xFF000000)
    private val inverseSurfaceLightMediumContrast = Color(0xFF2F3036)
    private val inverseOnSurfaceLightMediumContrast = Color(0xFFF1F0F7)
    private val inversePrimaryLightMediumContrast = Color(0xFFB4C5FF)
    private val surfaceDimLightMediumContrast = Color(0xFFC6C6CD)
    private val surfaceBrightLightMediumContrast = Color(0xFFFAF8FF)
    private val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
    private val surfaceContainerLowLightMediumContrast = Color(0xFFF4F3FA)
    private val surfaceContainerLightMediumContrast = Color(0xFFE8E7EF)
    private val surfaceContainerHighLightMediumContrast = Color(0xFFDDDCE3)
    private val surfaceContainerHighestLightMediumContrast = Color(0xFFD2D1D8)

    private val primaryLightHighContrast = Color(0xFF15295C)
    private val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
    private val primaryContainerLightHighContrast = Color(0xFF35477B)
    private val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
    private val secondaryLightHighContrast = Color(0xFF262C3D)
    private val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
    private val secondaryContainerLightHighContrast = Color(0xFF43495C)
    private val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
    private val tertiaryLightHighContrast = Color(0xFF402700)
    private val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
    private val tertiaryContainerLightHighContrast = Color(0xFF674100)
    private val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
    private val errorLightHighContrast = Color(0xFF600004)
    private val onErrorLightHighContrast = Color(0xFFFFFFFF)
    private val errorContainerLightHighContrast = Color(0xFF98000A)
    private val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
    private val backgroundLightHighContrast = Color(0xFFFAF8FF)
    private val onBackgroundLightHighContrast = Color(0xFF1A1B21)
    private val surfaceLightHighContrast = Color(0xFFFAF8FF)
    private val onSurfaceLightHighContrast = Color(0xFF000000)
    private val surfaceVariantLightHighContrast = Color(0xFFE2E2EC)
    private val onSurfaceVariantLightHighContrast = Color(0xFF000000)
    private val outlineLightHighContrast = Color(0xFF2A2C34)
    private val outlineVariantLightHighContrast = Color(0xFF474951)
    private val scrimLightHighContrast = Color(0xFF000000)
    private val inverseSurfaceLightHighContrast = Color(0xFF2F3036)
    private val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
    private val inversePrimaryLightHighContrast = Color(0xFFB4C5FF)
    private val surfaceDimLightHighContrast = Color(0xFFB9B8BF)
    private val surfaceBrightLightHighContrast = Color(0xFFFAF8FF)
    private val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
    private val surfaceContainerLowLightHighContrast = Color(0xFFF1F0F7)
    private val surfaceContainerLightHighContrast = Color(0xFFE3E2E9)
    private val surfaceContainerHighLightHighContrast = Color(0xFFD4D3DB)
    private val surfaceContainerHighestLightHighContrast = Color(0xFFC6C6CD)

    private val primaryDark = Color(0xFFB4C5FF)
    private val onPrimaryDark = Color(0xFF1A2D60)
    private val primaryContainerDark = Color(0xFF324478)
    private val onPrimaryContainerDark = Color(0xFFDBE1FF)
    private val secondaryDark = Color(0xFFC1C5DD)
    private val onSecondaryDark = Color(0xFF2A3042)
    private val secondaryContainerDark = Color(0xFF414659)
    private val onSecondaryContainerDark = Color(0xFFDDE1F9)
    private val tertiaryDark = Color(0xFFF6BC70)
    private val onTertiaryDark = Color(0xFF462B00)
    private val tertiaryContainerDark = Color(0xFF643F00)
    private val onTertiaryContainerDark = Color(0xFFFFDDB6)
    private val errorDark = Color(0xFFFFB4AB)
    private val onErrorDark = Color(0xFF690005)
    private val errorContainerDark = Color(0xFF93000A)
    private val onErrorContainerDark = Color(0xFFFFDAD6)
    private val backgroundDark = Color(0xFF121318)
    private val onBackgroundDark = Color(0xFFE3E2E9)
    private val surfaceDark = Color(0xFF121318)
    private val onSurfaceDark = Color(0xFFE3E2E9)
    private val surfaceVariantDark = Color(0xFF45464F)
    private val onSurfaceVariantDark = Color(0xFFC5C6D0)
    private val outlineDark = Color(0xFF8F909A)
    private val outlineVariantDark = Color(0xFF45464F)
    private val scrimDark = Color(0xFF000000)
    private val inverseSurfaceDark = Color(0xFFE3E2E9)
    private val inverseOnSurfaceDark = Color(0xFF2F3036)
    private val inversePrimaryDark = Color(0xFF4B5C92)
    private val surfaceDimDark = Color(0xFF121318)
    private val surfaceBrightDark = Color(0xFF38393F)
    private val surfaceContainerLowestDark = Color(0xFF0D0E13)
    private val surfaceContainerLowDark = Color(0xFF1A1B21)
    private val surfaceContainerDark = Color(0xFF1E1F25)
    private val surfaceContainerHighDark = Color(0xFF292A2F)
    private val surfaceContainerHighestDark = Color(0xFF34343A)

    private val primaryDarkMediumContrast = Color(0xFFD2DBFF)
    private val onPrimaryDarkMediumContrast = Color(0xFF0D2255)
    private val primaryContainerDarkMediumContrast = Color(0xFF7D8FC8)
    private val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
    private val secondaryDarkMediumContrast = Color(0xFFD7DBF3)
    private val onSecondaryDarkMediumContrast = Color(0xFF202536)
    private val secondaryContainerDarkMediumContrast = Color(0xFF8B90A5)
    private val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
    private val tertiaryDarkMediumContrast = Color(0xFFFFD5A3)
    private val onTertiaryDarkMediumContrast = Color(0xFF372100)
    private val tertiaryContainerDarkMediumContrast = Color(0xFFBA8740)
    private val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
    private val errorDarkMediumContrast = Color(0xFFFFD2CC)
    private val onErrorDarkMediumContrast = Color(0xFF540003)
    private val errorContainerDarkMediumContrast = Color(0xFFFF5449)
    private val onErrorContainerDarkMediumContrast = Color(0xFF000000)
    private val backgroundDarkMediumContrast = Color(0xFF121318)
    private val onBackgroundDarkMediumContrast = Color(0xFFE3E2E9)
    private val surfaceDarkMediumContrast = Color(0xFF121318)
    private val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
    private val surfaceVariantDarkMediumContrast = Color(0xFF45464F)
    private val onSurfaceVariantDarkMediumContrast = Color(0xFFDBDBE6)
    private val outlineDarkMediumContrast = Color(0xFFB1B1BB)
    private val outlineVariantDarkMediumContrast = Color(0xFF8F9099)
    private val scrimDarkMediumContrast = Color(0xFF000000)
    private val inverseSurfaceDarkMediumContrast = Color(0xFFE3E2E9)
    private val inverseOnSurfaceDarkMediumContrast = Color(0xFF292A2F)
    private val inversePrimaryDarkMediumContrast = Color(0xFF34467A)
    private val surfaceDimDarkMediumContrast = Color(0xFF121318)
    private val surfaceBrightDarkMediumContrast = Color(0xFF43444A)
    private val surfaceContainerLowestDarkMediumContrast = Color(0xFF06070C)
    private val surfaceContainerLowDarkMediumContrast = Color(0xFF1C1D23)
    private val surfaceContainerDarkMediumContrast = Color(0xFF27282D)
    private val surfaceContainerHighDarkMediumContrast = Color(0xFF313238)
    private val surfaceContainerHighestDarkMediumContrast = Color(0xFF3C3D43)

    private val primaryDarkHighContrast = Color(0xFFEDEFFF)
    private val onPrimaryDarkHighContrast = Color(0xFF000000)
    private val primaryContainerDarkHighContrast = Color(0xFFAFC1FD)
    private val onPrimaryContainerDarkHighContrast = Color(0xFF000928)
    private val secondaryDarkHighContrast = Color(0xFFEDEFFF)
    private val onSecondaryDarkHighContrast = Color(0xFF000000)
    private val secondaryContainerDarkHighContrast = Color(0xFFBDC2D9)
    private val onSecondaryContainerDarkHighContrast = Color(0xFF050A1B)
    private val tertiaryDarkHighContrast = Color(0xFFFFEDDB)
    private val onTertiaryDarkHighContrast = Color(0xFF000000)
    private val tertiaryContainerDarkHighContrast = Color(0xFFF2B86C)
    private val onTertiaryContainerDarkHighContrast = Color(0xFF140900)
    private val errorDarkHighContrast = Color(0xFFFFECE9)
    private val onErrorDarkHighContrast = Color(0xFF000000)
    private val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
    private val onErrorContainerDarkHighContrast = Color(0xFF220001)
    private val backgroundDarkHighContrast = Color(0xFF121318)
    private val onBackgroundDarkHighContrast = Color(0xFFE3E2E9)
    private val surfaceDarkHighContrast = Color(0xFF121318)
    private val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
    private val surfaceVariantDarkHighContrast = Color(0xFF45464F)
    private val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
    private val outlineDarkHighContrast = Color(0xFFEFEFFA)
    private val outlineVariantDarkHighContrast = Color(0xFFC1C2CC)
    private val scrimDarkHighContrast = Color(0xFF000000)
    private val inverseSurfaceDarkHighContrast = Color(0xFFE3E2E9)
    private val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
    private val inversePrimaryDarkHighContrast = Color(0xFF34467A)
    private val surfaceDimDarkHighContrast = Color(0xFF121318)
    private val surfaceBrightDarkHighContrast = Color(0xFF4F5056)
    private val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
    private val surfaceContainerLowDarkHighContrast = Color(0xFF1E1F25)
    private val surfaceContainerDarkHighContrast = Color(0xFF2F3036)
    private val surfaceContainerHighDarkHighContrast = Color(0xFF3A3B41)
    private val surfaceContainerHighestDarkHighContrast = Color(0xFF46464C)

    val lightScheme =
        lightColorScheme(
            primary = primaryLight,
            onPrimary = onPrimaryLight,
            primaryContainer = primaryContainerLight,
            onPrimaryContainer = onPrimaryContainerLight,
            secondary = secondaryLight,
            onSecondary = onSecondaryLight,
            secondaryContainer = secondaryContainerLight,
            onSecondaryContainer = onSecondaryContainerLight,
            tertiary = tertiaryLight,
            onTertiary = onTertiaryLight,
            tertiaryContainer = tertiaryContainerLight,
            onTertiaryContainer = onTertiaryContainerLight,
            error = errorLight,
            onError = onErrorLight,
            errorContainer = errorContainerLight,
            onErrorContainer = onErrorContainerLight,
            background = backgroundLight,
            onBackground = onBackgroundLight,
            surface = surfaceLight,
            onSurface = onSurfaceLight,
            surfaceVariant = surfaceVariantLight,
            onSurfaceVariant = onSurfaceVariantLight,
            outline = outlineLight,
            outlineVariant = outlineVariantLight,
            scrim = scrimLight,
            inverseSurface = inverseSurfaceLight,
            inverseOnSurface = inverseOnSurfaceLight,
            inversePrimary = inversePrimaryLight,
            surfaceDim = surfaceDimLight,
            surfaceBright = surfaceBrightLight,
            surfaceContainerLowest = surfaceContainerLowestLight,
            surfaceContainerLow = surfaceContainerLowLight,
            surfaceContainer = surfaceContainerLight,
            surfaceContainerHigh = surfaceContainerHighLight,
            surfaceContainerHighest = surfaceContainerHighestLight,
        )

    val darkScheme =
        darkColorScheme(
            primary = primaryDark,
            onPrimary = onPrimaryDark,
            primaryContainer = primaryContainerDark,
            onPrimaryContainer = onPrimaryContainerDark,
            secondary = secondaryDark,
            onSecondary = onSecondaryDark,
            secondaryContainer = secondaryContainerDark,
            onSecondaryContainer = onSecondaryContainerDark,
            tertiary = tertiaryDark,
            onTertiary = onTertiaryDark,
            tertiaryContainer = tertiaryContainerDark,
            onTertiaryContainer = onTertiaryContainerDark,
            error = errorDark,
            onError = onErrorDark,
            errorContainer = errorContainerDark,
            onErrorContainer = onErrorContainerDark,
            background = backgroundDark,
            onBackground = onBackgroundDark,
            surface = surfaceDark,
            onSurface = onSurfaceDark,
            surfaceVariant = surfaceVariantDark,
            onSurfaceVariant = onSurfaceVariantDark,
            outline = outlineDark,
            outlineVariant = outlineVariantDark,
            scrim = scrimDark,
            inverseSurface = inverseSurfaceDark,
            inverseOnSurface = inverseOnSurfaceDark,
            inversePrimary = inversePrimaryDark,
            surfaceDim = surfaceDimDark,
            surfaceBright = surfaceBrightDark,
            surfaceContainerLowest = surfaceContainerLowestDark,
            surfaceContainerLow = surfaceContainerLowDark,
            surfaceContainer = surfaceContainerDark,
            surfaceContainerHigh = surfaceContainerHighDark,
            surfaceContainerHighest = surfaceContainerHighestDark,
        )

    private val mediumContrastLightColorScheme =
        lightColorScheme(
            primary = primaryLightMediumContrast,
            onPrimary = onPrimaryLightMediumContrast,
            primaryContainer = primaryContainerLightMediumContrast,
            onPrimaryContainer = onPrimaryContainerLightMediumContrast,
            secondary = secondaryLightMediumContrast,
            onSecondary = onSecondaryLightMediumContrast,
            secondaryContainer = secondaryContainerLightMediumContrast,
            onSecondaryContainer = onSecondaryContainerLightMediumContrast,
            tertiary = tertiaryLightMediumContrast,
            onTertiary = onTertiaryLightMediumContrast,
            tertiaryContainer = tertiaryContainerLightMediumContrast,
            onTertiaryContainer = onTertiaryContainerLightMediumContrast,
            error = errorLightMediumContrast,
            onError = onErrorLightMediumContrast,
            errorContainer = errorContainerLightMediumContrast,
            onErrorContainer = onErrorContainerLightMediumContrast,
            background = backgroundLightMediumContrast,
            onBackground = onBackgroundLightMediumContrast,
            surface = surfaceLightMediumContrast,
            onSurface = onSurfaceLightMediumContrast,
            surfaceVariant = surfaceVariantLightMediumContrast,
            onSurfaceVariant = onSurfaceVariantLightMediumContrast,
            outline = outlineLightMediumContrast,
            outlineVariant = outlineVariantLightMediumContrast,
            scrim = scrimLightMediumContrast,
            inverseSurface = inverseSurfaceLightMediumContrast,
            inverseOnSurface = inverseOnSurfaceLightMediumContrast,
            inversePrimary = inversePrimaryLightMediumContrast,
            surfaceDim = surfaceDimLightMediumContrast,
            surfaceBright = surfaceBrightLightMediumContrast,
            surfaceContainerLowest = surfaceContainerLowestLightMediumContrast,
            surfaceContainerLow = surfaceContainerLowLightMediumContrast,
            surfaceContainer = surfaceContainerLightMediumContrast,
            surfaceContainerHigh = surfaceContainerHighLightMediumContrast,
            surfaceContainerHighest = surfaceContainerHighestLightMediumContrast,
        )

    private val highContrastLightColorScheme =
        lightColorScheme(
            primary = primaryLightHighContrast,
            onPrimary = onPrimaryLightHighContrast,
            primaryContainer = primaryContainerLightHighContrast,
            onPrimaryContainer = onPrimaryContainerLightHighContrast,
            secondary = secondaryLightHighContrast,
            onSecondary = onSecondaryLightHighContrast,
            secondaryContainer = secondaryContainerLightHighContrast,
            onSecondaryContainer = onSecondaryContainerLightHighContrast,
            tertiary = tertiaryLightHighContrast,
            onTertiary = onTertiaryLightHighContrast,
            tertiaryContainer = tertiaryContainerLightHighContrast,
            onTertiaryContainer = onTertiaryContainerLightHighContrast,
            error = errorLightHighContrast,
            onError = onErrorLightHighContrast,
            errorContainer = errorContainerLightHighContrast,
            onErrorContainer = onErrorContainerLightHighContrast,
            background = backgroundLightHighContrast,
            onBackground = onBackgroundLightHighContrast,
            surface = surfaceLightHighContrast,
            onSurface = onSurfaceLightHighContrast,
            surfaceVariant = surfaceVariantLightHighContrast,
            onSurfaceVariant = onSurfaceVariantLightHighContrast,
            outline = outlineLightHighContrast,
            outlineVariant = outlineVariantLightHighContrast,
            scrim = scrimLightHighContrast,
            inverseSurface = inverseSurfaceLightHighContrast,
            inverseOnSurface = inverseOnSurfaceLightHighContrast,
            inversePrimary = inversePrimaryLightHighContrast,
            surfaceDim = surfaceDimLightHighContrast,
            surfaceBright = surfaceBrightLightHighContrast,
            surfaceContainerLowest = surfaceContainerLowestLightHighContrast,
            surfaceContainerLow = surfaceContainerLowLightHighContrast,
            surfaceContainer = surfaceContainerLightHighContrast,
            surfaceContainerHigh = surfaceContainerHighLightHighContrast,
            surfaceContainerHighest = surfaceContainerHighestLightHighContrast,
        )

    private val mediumContrastDarkColorScheme =
        darkColorScheme(
            primary = primaryDarkMediumContrast,
            onPrimary = onPrimaryDarkMediumContrast,
            primaryContainer = primaryContainerDarkMediumContrast,
            onPrimaryContainer = onPrimaryContainerDarkMediumContrast,
            secondary = secondaryDarkMediumContrast,
            onSecondary = onSecondaryDarkMediumContrast,
            secondaryContainer = secondaryContainerDarkMediumContrast,
            onSecondaryContainer = onSecondaryContainerDarkMediumContrast,
            tertiary = tertiaryDarkMediumContrast,
            onTertiary = onTertiaryDarkMediumContrast,
            tertiaryContainer = tertiaryContainerDarkMediumContrast,
            onTertiaryContainer = onTertiaryContainerDarkMediumContrast,
            error = errorDarkMediumContrast,
            onError = onErrorDarkMediumContrast,
            errorContainer = errorContainerDarkMediumContrast,
            onErrorContainer = onErrorContainerDarkMediumContrast,
            background = backgroundDarkMediumContrast,
            onBackground = onBackgroundDarkMediumContrast,
            surface = surfaceDarkMediumContrast,
            onSurface = onSurfaceDarkMediumContrast,
            surfaceVariant = surfaceVariantDarkMediumContrast,
            onSurfaceVariant = onSurfaceVariantDarkMediumContrast,
            outline = outlineDarkMediumContrast,
            outlineVariant = outlineVariantDarkMediumContrast,
            scrim = scrimDarkMediumContrast,
            inverseSurface = inverseSurfaceDarkMediumContrast,
            inverseOnSurface = inverseOnSurfaceDarkMediumContrast,
            inversePrimary = inversePrimaryDarkMediumContrast,
            surfaceDim = surfaceDimDarkMediumContrast,
            surfaceBright = surfaceBrightDarkMediumContrast,
            surfaceContainerLowest = surfaceContainerLowestDarkMediumContrast,
            surfaceContainerLow = surfaceContainerLowDarkMediumContrast,
            surfaceContainer = surfaceContainerDarkMediumContrast,
            surfaceContainerHigh = surfaceContainerHighDarkMediumContrast,
            surfaceContainerHighest = surfaceContainerHighestDarkMediumContrast,
        )

    private val highContrastDarkColorScheme =
        darkColorScheme(
            primary = primaryDarkHighContrast,
            onPrimary = onPrimaryDarkHighContrast,
            primaryContainer = primaryContainerDarkHighContrast,
            onPrimaryContainer = onPrimaryContainerDarkHighContrast,
            secondary = secondaryDarkHighContrast,
            onSecondary = onSecondaryDarkHighContrast,
            secondaryContainer = secondaryContainerDarkHighContrast,
            onSecondaryContainer = onSecondaryContainerDarkHighContrast,
            tertiary = tertiaryDarkHighContrast,
            onTertiary = onTertiaryDarkHighContrast,
            tertiaryContainer = tertiaryContainerDarkHighContrast,
            onTertiaryContainer = onTertiaryContainerDarkHighContrast,
            error = errorDarkHighContrast,
            onError = onErrorDarkHighContrast,
            errorContainer = errorContainerDarkHighContrast,
            onErrorContainer = onErrorContainerDarkHighContrast,
            background = backgroundDarkHighContrast,
            onBackground = onBackgroundDarkHighContrast,
            surface = surfaceDarkHighContrast,
            onSurface = onSurfaceDarkHighContrast,
            surfaceVariant = surfaceVariantDarkHighContrast,
            onSurfaceVariant = onSurfaceVariantDarkHighContrast,
            outline = outlineDarkHighContrast,
            outlineVariant = outlineVariantDarkHighContrast,
            scrim = scrimDarkHighContrast,
            inverseSurface = inverseSurfaceDarkHighContrast,
            inverseOnSurface = inverseOnSurfaceDarkHighContrast,
            inversePrimary = inversePrimaryDarkHighContrast,
            surfaceDim = surfaceDimDarkHighContrast,
            surfaceBright = surfaceBrightDarkHighContrast,
            surfaceContainerLowest = surfaceContainerLowestDarkHighContrast,
            surfaceContainerLow = surfaceContainerLowDarkHighContrast,
            surfaceContainer = surfaceContainerDarkHighContrast,
            surfaceContainerHigh = surfaceContainerHighDarkHighContrast,
            surfaceContainerHighest = surfaceContainerHighestDarkHighContrast,
        )
}
